
import json
import os
from datetime import datetime

def save_case(case_data, label="unknown"):
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    case_id = f"case_{label}_{timestamp}"
    folder = "cases"
    os.makedirs(folder, exist_ok=True)

    # Save JSON
    json_path = os.path.join(folder, f"{case_id}.json")
    with open(json_path, "w") as f:
        json.dump(case_data, f, indent=4)

    # Save Markdown
    md_path = os.path.join(folder, f"{case_id}.md")
    with open(md_path, "w") as f:
        f.write(f"# InfoHawk Case Report: {label}\n\n")
        f.write(f"**Timestamp:** {timestamp}\n\n")
        f.write(f"**Summary:**\n")
        for k, v in case_data.items():
            if isinstance(v, list):
                f.write(f"\n### {k.capitalize()}\n")
                for item in v:
                    f.write(f"- {item}\n")
            else:
                f.write(f"- **{k}**: {v}\n")
        f.write("\n\n---\n**Report generated by InfoHawk 🦅 - by Zadwen**")

    return case_id
